cmake_minimum_required(VERSION 4.2)
project(Prata_Study CXX)

set(CMAKE_CXX_STANDARD 20)

# Подключаем ваши уроки к кнопке запуска
add_executable(Listing_2_1 Lessons_cpp/Chapter_2/Listing_2_1/main.cpp)
add_executable(Listing_2_2 Lessons_cpp/Chapter_2/Listing_2_2/main.cpp)
add_executable(Listing_2_3 Lessons_cpp/Chapter_2/Listing_2_3/main.cpp)
add_executable(Listing_2_4 Lessons_cpp/Chapter_2/Listing_2_4/main.cpp)


